"""Add position and motion

Revision ID: 42a6f947500c
Revises: 64748555a0cd
Create Date: 2018-11-06 14:05:05.337188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a6f947500c'
down_revision = '64748555a0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rssi_readings', sa.Column('motion', sa.Integer(), nullable=True))
    op.add_column('rssi_readings', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rssi_readings', 'position')
    op.drop_column('rssi_readings', 'motion')
    # ### end Alembic commands ###
