"""Opposite Badge ID

Revision ID: 64748555a0cd
Revises: 3015a0e80a69
Create Date: 2018-11-03 12:18:54.918444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64748555a0cd'
down_revision = '3015a0e80a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rssi_readings', sa.Column('opposite_badge_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rssi_readings', 'opposite_badge_id')
    # ### end Alembic commands ###
