def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('landing', '/')
    config.add_route('docs__rssi_readings', '/api-docs/rssi_readings')
    config.add_route('training_runs__index', '/training_runs')
    config.add_route('training_runs__new', '/training_runs/new')
    config.add_route('training_runs__bulk_start', '/training_runs/bulk_start', request_method='POST')
    config.add_route('training_runs__bulk_end', '/training_runs/bulk_end')
    config.add_route('training_runs__bulk_stats', '/training_runs/bulk_stats')
    config.add_route('rssi_readings', '/rssi_readings', request_method='GET')
    config.add_route('badge_show', '/badges/{id}', request_method='GET')
    config.add_route('badge_fetch', '/badges/{id}/fetch', request_method='GET')
    config.add_route('home', '/original_home')
    config.add_route('create_rssi_reading', '/rssi_readings', request_method='POST')
